name: Deploy Interactive UI to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ''

      - name: Install dependencies and Compile Contracts
        run: |
          npm install
          node compile.js

      - name: Prepare Ethers.js for Deployment
        run: |
          mkdir -p ./lib
          cp ./node_modules/ethers/dist/ethers.umd.min.js ./lib/

      # این مرحله کلیدی، حالا تمام فایل‌های لازم را کپی می‌کند
      - name: Organize files for deployment
        run: |
          mkdir -p public/node_modules
          cp index.html ./public/
          cp deploy-ui.js ./public/
          cp artifacts.json ./public/
          cp verification_*.json ./public/
          cp -r contracts ./public/
          cp -r lib ./public/
          cp -r node_modules/@openzeppelin ./public/node_modules/

      - name: Deploy UI to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy-contract
          publish_dir: ./public
          force_orphan: true
