name: Deploy Interactive UI to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python and Solidity dependencies
        run: |
          pip install -r requirements.txt
          npm install @openzeppelin/contracts

      - name: Build project artifacts
        run: python build.py

      - name: Prepare Ethers.js for Deployment
        run: |
          mkdir -p lib
          curl -L https://cdn.jsdelivr.net/npm/ethers@5.7.2/dist/ethers.umd.min.js -o lib/ethers.umd.min.js

      - name: Organize files for deployment
        run: |
          mkdir -p public
          cp index.html ./public/
          cp deploy-ui.js ./public/
          cp artifacts.json ./public/
          cp -r contracts ./public/
          cp -r lib ./public/
          # --- این خط کلیدی در نسخه قبل جا افتاده بود ---
          cp verification_*.json ./public/

      - name: Deploy UI to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy-contract
          publish_dir: ./public
          force_orphan: true
